version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: parth
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://parth:1234@localhost/users
    ports:
      - "8000:8000"   # FastAPI port
      - "8501:8501"   # Streamlit port
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
