version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: parth
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: fastapi_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://parth:1234@localhost/users
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: streamlit_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  postgres_data:
