version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: parth
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # Mount entire directory instead of a single file
    networks:
      - backend
    restart: always  # Ensures DB restarts if it fails

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://parth:1234@db/users  # Use 'db' as hostname
    ports:
      - "8000:8000"  # FastAPI port
      - "8501:8501"  # Streamlit port
    depends_on:
      - db
    networks:
      - backend
    restart: always  # Ensures app restarts if it fails
    volumes:
      - ./wheelhouse:/app/wheelhouse  # Mount wheelhouse for faster dependency installation

networks:
  backend:
    driver: bridge
